pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    parameters{
    booleanParam(defaultValue: false, description: "Enable service?", name: "myBoolean")
    }
    stages {
        stage("Hello")
        {
         steps{
            echo "Hey there"
         }
        }
        stage("Demo")
        {
        steps{
            echo "booleanParam is set to : ${params.myBoolean}"
        }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
