pipeline {
    agent any
    tools {
        maven 'M3' // This must match the name you gave in Tools
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage("Hello")
        {
         steps{
            echo "Hey there"
         }
        }
        stage('Build') {
            steps {
                sh 'export PATH=$PATH:/usr/local/bin:/usr/bin'
                sh 'mvn -B -DskipTests clean package'
                
            }
        }
        stage('Test') {
            steps {
                sh 'export PATH=$PATH:/usr/local/bin:/usr/bin'
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
